var namespaceWolfstagInteractive_1_1WitWeaver =
[
    [ "SaveSystem", "namespaceWolfstagInteractive_1_1WitWeaver_1_1SaveSystem.html", "namespaceWolfstagInteractive_1_1WitWeaver_1_1SaveSystem" ],
    [ "AnimatedCharacterRepresentationData", "classWolfstagInteractive_1_1WitWeaver_1_1AnimatedCharacterRepresentationData.html", "classWolfstagInteractive_1_1WitWeaver_1_1AnimatedCharacterRepresentationData" ],
    [ "AnimatedExpressionMapping", "classWolfstagInteractive_1_1WitWeaver_1_1AnimatedExpressionMapping.html", "classWolfstagInteractive_1_1WitWeaver_1_1AnimatedExpressionMapping" ],
    [ "AnimatedExpressionPayload", "classWolfstagInteractive_1_1WitWeaver_1_1AnimatedExpressionPayload.html", "classWolfstagInteractive_1_1WitWeaver_1_1AnimatedExpressionPayload" ],
    [ "AnimatedPlaybackContext", "structWolfstagInteractive_1_1WitWeaver_1_1AnimatedPlaybackContext.html", "structWolfstagInteractive_1_1WitWeaver_1_1AnimatedPlaybackContext" ],
    [ "AnimatorExpressionMapping", "classWolfstagInteractive_1_1WitWeaver_1_1AnimatorExpressionMapping.html", "classWolfstagInteractive_1_1WitWeaver_1_1AnimatorExpressionMapping" ],
    [ "AnimatorPrefabAnimationPayload", "classWolfstagInteractive_1_1WitWeaver_1_1AnimatorPrefabAnimationPayload.html", "classWolfstagInteractive_1_1WitWeaver_1_1AnimatorPrefabAnimationPayload" ],
    [ "BaseDialogueLineAction", "classWolfstagInteractive_1_1WitWeaver_1_1BaseDialogueLineAction.html", "classWolfstagInteractive_1_1WitWeaver_1_1BaseDialogueLineAction" ],
    [ "BaseExpressionAction", "classWolfstagInteractive_1_1WitWeaver_1_1BaseExpressionAction.html", "classWolfstagInteractive_1_1WitWeaver_1_1BaseExpressionAction" ],
    [ "BaseWitWeaverBranchCondition", "classWolfstagInteractive_1_1WitWeaver_1_1BaseWitWeaverBranchCondition.html", "classWolfstagInteractive_1_1WitWeaver_1_1BaseWitWeaverBranchCondition" ],
    [ "BlendShapeExpressionMapping", "classWolfstagInteractive_1_1WitWeaver_1_1BlendShapeExpressionMapping.html", "classWolfstagInteractive_1_1WitWeaver_1_1BlendShapeExpressionMapping" ],
    [ "BlendShapeTarget", "classWolfstagInteractive_1_1WitWeaver_1_1BlendShapeTarget.html", "classWolfstagInteractive_1_1WitWeaver_1_1BlendShapeTarget" ],
    [ "CameraRelativeBehaviour", "classWolfstagInteractive_1_1WitWeaver_1_1CameraRelativeBehaviour.html", "classWolfstagInteractive_1_1WitWeaver_1_1CameraRelativeBehaviour" ],
    [ "CharacterBehaviourContext", "structWolfstagInteractive_1_1WitWeaver_1_1CharacterBehaviourContext.html", "structWolfstagInteractive_1_1WitWeaver_1_1CharacterBehaviourContext" ],
    [ "CharacterRepresentationBase", "classWolfstagInteractive_1_1WitWeaver_1_1CharacterRepresentationBase.html", "classWolfstagInteractive_1_1WitWeaver_1_1CharacterRepresentationBase" ],
    [ "ChoiceResult", "classWolfstagInteractive_1_1WitWeaver_1_1ChoiceResult.html", "classWolfstagInteractive_1_1WitWeaver_1_1ChoiceResult" ],
    [ "ContainerAliasSelectorAttribute", "classWolfstagInteractive_1_1WitWeaver_1_1ContainerAliasSelectorAttribute.html", "classWolfstagInteractive_1_1WitWeaver_1_1ContainerAliasSelectorAttribute" ],
    [ "ContainerInput", "classWolfstagInteractive_1_1WitWeaver_1_1ContainerInput.html", "classWolfstagInteractive_1_1WitWeaver_1_1ContainerInput" ],
    [ "ConversationBranchResult", "structWolfstagInteractive_1_1WitWeaver_1_1ConversationBranchResult.html", "structWolfstagInteractive_1_1WitWeaver_1_1ConversationBranchResult" ],
    [ "ConversationContainer", "classWolfstagInteractive_1_1WitWeaver_1_1ConversationContainer.html", "classWolfstagInteractive_1_1WitWeaver_1_1ConversationContainer" ],
    [ "ConversationContainerRuntime", "classWolfstagInteractive_1_1WitWeaver_1_1ConversationContainerRuntime.html", "classWolfstagInteractive_1_1WitWeaver_1_1ConversationContainerRuntime" ],
    [ "DebugLogExpressionAction", "classWolfstagInteractive_1_1WitWeaver_1_1DebugLogExpressionAction.html", "classWolfstagInteractive_1_1WitWeaver_1_1DebugLogExpressionAction" ],
    [ "DefaultConversationContext", "classWolfstagInteractive_1_1WitWeaver_1_1DefaultConversationContext.html", "classWolfstagInteractive_1_1WitWeaver_1_1DefaultConversationContext" ],
    [ "DialogueHistoryEntry", "classWolfstagInteractive_1_1WitWeaver_1_1DialogueHistoryEntry.html", "classWolfstagInteractive_1_1WitWeaver_1_1DialogueHistoryEntry" ],
    [ "DialogueHistoryRendererContext", "structWolfstagInteractive_1_1WitWeaver_1_1DialogueHistoryRendererContext.html", "structWolfstagInteractive_1_1WitWeaver_1_1DialogueHistoryRendererContext" ],
    [ "DialogueLineDisplayOptions", "classWolfstagInteractive_1_1WitWeaver_1_1DialogueLineDisplayOptions.html", "classWolfstagInteractive_1_1WitWeaver_1_1DialogueLineDisplayOptions" ],
    [ "DialogueYamlConfig", "classWolfstagInteractive_1_1WitWeaver_1_1DialogueYamlConfig.html", "classWolfstagInteractive_1_1WitWeaver_1_1DialogueYamlConfig" ],
    [ "ExpressionActionContext", "structWolfstagInteractive_1_1WitWeaver_1_1ExpressionActionContext.html", "structWolfstagInteractive_1_1WitWeaver_1_1ExpressionActionContext" ],
    [ "ExpressionIDSelectorAttribute", "classWolfstagInteractive_1_1WitWeaver_1_1ExpressionIDSelectorAttribute.html", "classWolfstagInteractive_1_1WitWeaver_1_1ExpressionIDSelectorAttribute" ],
    [ "ExternalBehaviour", "classWolfstagInteractive_1_1WitWeaver_1_1ExternalBehaviour.html", "classWolfstagInteractive_1_1WitWeaver_1_1ExternalBehaviour" ],
    [ "FlipbookAnimationPayload", "classWolfstagInteractive_1_1WitWeaver_1_1FlipbookAnimationPayload.html", "classWolfstagInteractive_1_1WitWeaver_1_1FlipbookAnimationPayload" ],
    [ "FollowTargetBehaviour", "classWolfstagInteractive_1_1WitWeaver_1_1FollowTargetBehaviour.html", "classWolfstagInteractive_1_1WitWeaver_1_1FollowTargetBehaviour" ],
    [ "GameObjectHelper", "classWolfstagInteractive_1_1WitWeaver_1_1GameObjectHelper.html", "classWolfstagInteractive_1_1WitWeaver_1_1GameObjectHelper" ],
    [ "GameObjectReference", "classWolfstagInteractive_1_1WitWeaver_1_1GameObjectReference.html", "classWolfstagInteractive_1_1WitWeaver_1_1GameObjectReference" ],
    [ "GraphConversationInput", "classWolfstagInteractive_1_1WitWeaver_1_1GraphConversationInput.html", "classWolfstagInteractive_1_1WitWeaver_1_1GraphConversationInput" ],
    [ "IAnimatedExpressionPlayback", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IAnimatedExpressionPlayback.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IAnimatedExpressionPlayback" ],
    [ "IAnimatedPortraitSurface", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IAnimatedPortraitSurface.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IAnimatedPortraitSurface" ],
    [ "IConversationContext", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IConversationContext.html", null ],
    [ "IDialogueHistoryOutput", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IDialogueHistoryOutput.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IDialogueHistoryOutput" ],
    [ "IDialogueHistoryOutputPrefab", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IDialogueHistoryOutputPrefab.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IDialogueHistoryOutputPrefab" ],
    [ "IExpressionCatalogProvider", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IExpressionCatalogProvider.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IExpressionCatalogProvider" ],
    [ "IUIFoundation", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IUIFoundation.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IUIFoundation" ],
    [ "IWitWeaverAudioProvider", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverAudioProvider.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverAudioProvider" ],
    [ "IWitWeaverBranchCondition", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverBranchCondition.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverBranchCondition" ],
    [ "IWitWeaverCharacterDisplay", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverCharacterDisplay.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverCharacterDisplay" ],
    [ "IWitWeaverFadeIn", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverFadeIn.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverFadeIn" ],
    [ "IWitWeaverFadeOut", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverFadeOut.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverFadeOut" ],
    [ "IWitWeaverHistoryRenderer", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverHistoryRenderer.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverHistoryRenderer" ],
    [ "IWitWeaverInput", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverInput.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverInput" ],
    [ "IWitWeaverLanguageSettingsLoader", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverLanguageSettingsLoader.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverLanguageSettingsLoader" ],
    [ "IWitWeaverRepresentationInitializable", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverRepresentationInitializable.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverRepresentationInitializable" ],
    [ "IWitWeaverRunner", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverRunner.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverRunner" ],
    [ "IWitWeaverSpreadsheetReader", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverSpreadsheetReader.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverSpreadsheetReader" ],
    [ "IWitWeaverStartContextProvider", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverStartContextProvider.html", "interfaceWolfstagInteractive_1_1WitWeaver_1_1IWitWeaverStartContextProvider" ],
    [ "LineIDSelectorAttribute", "classWolfstagInteractive_1_1WitWeaver_1_1LineIDSelectorAttribute.html", null ],
    [ "LocalizedDialogueResult", "classWolfstagInteractive_1_1WitWeaver_1_1LocalizedDialogueResult.html", "classWolfstagInteractive_1_1WitWeaver_1_1LocalizedDialogueResult" ],
    [ "PagedListAttribute", "classWolfstagInteractive_1_1WitWeaver_1_1PagedListAttribute.html", "classWolfstagInteractive_1_1WitWeaver_1_1PagedListAttribute" ],
    [ "ParticipantConfigurationSlot", "classWolfstagInteractive_1_1WitWeaver_1_1ParticipantConfigurationSlot.html", "classWolfstagInteractive_1_1WitWeaver_1_1ParticipantConfigurationSlot" ],
    [ "PlainTextHistoryRenderer", "classWolfstagInteractive_1_1WitWeaver_1_1PlainTextHistoryRenderer.html", "classWolfstagInteractive_1_1WitWeaver_1_1PlainTextHistoryRenderer" ],
    [ "PlayOneShotAudioExpressionAction", "classWolfstagInteractive_1_1WitWeaver_1_1PlayOneShotAudioExpressionAction.html", "classWolfstagInteractive_1_1WitWeaver_1_1PlayOneShotAudioExpressionAction" ],
    [ "PrefabCharacterConfigurationEntry", "classWolfstagInteractive_1_1WitWeaver_1_1PrefabCharacterConfigurationEntry.html", "classWolfstagInteractive_1_1WitWeaver_1_1PrefabCharacterConfigurationEntry" ],
    [ "PrefabCharacterRepresentationData", "classWolfstagInteractive_1_1WitWeaver_1_1PrefabCharacterRepresentationData.html", "classWolfstagInteractive_1_1WitWeaver_1_1PrefabCharacterRepresentationData" ],
    [ "PrefabDialogueHistoryOutput", "classWolfstagInteractive_1_1WitWeaver_1_1PrefabDialogueHistoryOutput.html", "classWolfstagInteractive_1_1WitWeaver_1_1PrefabDialogueHistoryOutput" ],
    [ "PrefabExpressionMapping", "classWolfstagInteractive_1_1WitWeaver_1_1PrefabExpressionMapping.html", "classWolfstagInteractive_1_1WitWeaver_1_1PrefabExpressionMapping" ],
    [ "PrefabHistoryRenderer", "classWolfstagInteractive_1_1WitWeaver_1_1PrefabHistoryRenderer.html", "classWolfstagInteractive_1_1WitWeaver_1_1PrefabHistoryRenderer" ],
    [ "PreprocessorResult", "classWolfstagInteractive_1_1WitWeaver_1_1PreprocessorResult.html", "classWolfstagInteractive_1_1WitWeaver_1_1PreprocessorResult" ],
    [ "RepresentationPair", "classWolfstagInteractive_1_1WitWeaver_1_1RepresentationPair.html", "classWolfstagInteractive_1_1WitWeaver_1_1RepresentationPair" ],
    [ "RichTextHistoryRenderer", "classWolfstagInteractive_1_1WitWeaver_1_1RichTextHistoryRenderer.html", "classWolfstagInteractive_1_1WitWeaver_1_1RichTextHistoryRenderer" ],
    [ "SequencedBehaviour", "classWolfstagInteractive_1_1WitWeaver_1_1SequencedBehaviour.html", "classWolfstagInteractive_1_1WitWeaver_1_1SequencedBehaviour" ],
    [ "SimplePrefabRepresentationDisplay", "classWolfstagInteractive_1_1WitWeaver_1_1SimplePrefabRepresentationDisplay.html", "classWolfstagInteractive_1_1WitWeaver_1_1SimplePrefabRepresentationDisplay" ],
    [ "SingleConversationInput", "classWolfstagInteractive_1_1WitWeaver_1_1SingleConversationInput.html", "classWolfstagInteractive_1_1WitWeaver_1_1SingleConversationInput" ],
    [ "SpreadsheetRowConfig", "classWolfstagInteractive_1_1WitWeaver_1_1SpreadsheetRowConfig.html", "classWolfstagInteractive_1_1WitWeaver_1_1SpreadsheetRowConfig" ],
    [ "SpriteCharacterRepresentationData", "classWolfstagInteractive_1_1WitWeaver_1_1SpriteCharacterRepresentationData.html", "classWolfstagInteractive_1_1WitWeaver_1_1SpriteCharacterRepresentationData" ],
    [ "SpriteExpressionMapping", "classWolfstagInteractive_1_1WitWeaver_1_1SpriteExpressionMapping.html", "classWolfstagInteractive_1_1WitWeaver_1_1SpriteExpressionMapping" ],
    [ "TMPDialogueHistoryOutput", "classWolfstagInteractive_1_1WitWeaver_1_1TMPDialogueHistoryOutput.html", "classWolfstagInteractive_1_1WitWeaver_1_1TMPDialogueHistoryOutput" ],
    [ "TransformLerpBehaviour", "classWolfstagInteractive_1_1WitWeaver_1_1TransformLerpBehaviour.html", "classWolfstagInteractive_1_1WitWeaver_1_1TransformLerpBehaviour" ],
    [ "WitWeaver", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaver.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaver" ],
    [ "WitWeaverActionOnlyDisplay", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverActionOnlyDisplay.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverActionOnlyDisplay" ],
    [ "WitWeaverAddressablesUtil", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverAddressablesUtil.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverAddressablesUtil" ],
    [ "WitWeaverAnimatedPortraitPlayer", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverAnimatedPortraitPlayer.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverAnimatedPortraitPlayer" ],
    [ "WitWeaverAnimatorBehaviour", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverAnimatorBehaviour.html", null ],
    [ "WitWeaverAnimatorDisplay", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverAnimatorDisplay.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverAnimatorDisplay" ],
    [ "WitWeaverAudioEventKeyReference", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverAudioEventKeyReference.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverAudioEventKeyReference" ],
    [ "WitWeaverAudioManifest", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverAudioManifest.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverAudioManifest" ],
    [ "WitWeaverAudioReference", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverAudioReference.html", null ],
    [ "WitWeaverBlendShapeDisplay", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverBlendShapeDisplay.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverBlendShapeDisplay" ],
    [ "WitWeaverCameraRelativePosition", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverCameraRelativePosition.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverCameraRelativePosition" ],
    [ "WitWeaverCharacterBehaviour", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverCharacterBehaviour.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverCharacterBehaviour" ],
    [ "WitWeaverCharacterDisplayBase", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverCharacterDisplayBase.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverCharacterDisplayBase" ],
    [ "WitWeaverCharacterProfileBaseData", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverCharacterProfileBaseData.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverCharacterProfileBaseData" ],
    [ "WitWeaverConversationData", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverConversationData.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverConversationData" ],
    [ "WitWeaverDialogueHistoryUI", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueHistoryUI.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueHistoryUI" ],
    [ "WitWeaverDialogueLineActionDialogueLineActionGroup", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLineActionDialogueLineActionGroup.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLineActionDialogueLineActionGroup" ],
    [ "WitWeaverDialogueLineActionEnableDisableGameObject", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLineActionEnableDisableGameObject.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLineActionEnableDisableGameObject" ],
    [ "WitWeaverDialogueLineActionFadeInOutSpriteRenderer", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLineActionFadeInOutSpriteRenderer.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLineActionFadeInOutSpriteRenderer" ],
    [ "WitWeaverDialogueLineActionInstantiatePrefab", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLineActionInstantiatePrefab.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLineActionInstantiatePrefab" ],
    [ "WitWeaverDialogueLineActionModifyTransform", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLineActionModifyTransform.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLineActionModifyTransform" ],
    [ "WitWeaverDialogueLineActionPlayAudioClip", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLineActionPlayAudioClip.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLineActionPlayAudioClip" ],
    [ "WitWeaverDialogueLocalizationHandler", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLocalizationHandler.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverDialogueLocalizationHandler" ],
    [ "WitWeaverFollowTarget", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverFollowTarget.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverFollowTarget" ],
    [ "WitWeaverHistoryRendererProfile", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverHistoryRendererProfile.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverHistoryRendererProfile" ],
    [ "WitWeaverHistoryRendererRegistry", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverHistoryRendererRegistry.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverHistoryRendererRegistry" ],
    [ "WitWeaverLanguageManager", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverLanguageManager.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverLanguageManager" ],
    [ "WitWeaverLanguageSettings", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverLanguageSettings.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverLanguageSettings" ],
    [ "WitWeaverLanguageSettingsLoader", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverLanguageSettingsLoader.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverLanguageSettingsLoader" ],
    [ "WitWeaverLineID", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverLineID.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverLineID" ],
    [ "WitWeaverLineIDUtility", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverLineIDUtility.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverLineIDUtility" ],
    [ "WitWeaverPrefabPool", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverPrefabPool.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverPrefabPool" ],
    [ "WitWeaverPrefabRepresentationSpawner", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverPrefabRepresentationSpawner.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverPrefabRepresentationSpawner" ],
    [ "WitWeaverSampleUI3D", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSampleUI3D.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSampleUI3D" ],
    [ "WitWeaverSampleUICanvas", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSampleUICanvas.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSampleUICanvas" ],
    [ "WitWeaverSceneCharacterRegistrant", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSceneCharacterRegistrant.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSceneCharacterRegistrant" ],
    [ "WitWeaverSceneCharacterRegistry", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSceneCharacterRegistry.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSceneCharacterRegistry" ],
    [ "WitWeaverSettings", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSettings.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSettings" ],
    [ "WitWeaverSimpleFade", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSimpleFade.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSimpleFade" ],
    [ "WitWeaverSpawnPoint", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSpawnPoint.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSpawnPoint" ],
    [ "WitWeaverSpawnPointRegistry", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSpawnPointRegistry.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverSpawnPointRegistry" ],
    [ "WitWeaverStartContext", "structWolfstagInteractive_1_1WitWeaver_1_1WitWeaverStartContext.html", "structWolfstagInteractive_1_1WitWeaver_1_1WitWeaverStartContext" ],
    [ "WitWeaverTransformLerp", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverTransformLerp.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverTransformLerp" ],
    [ "WitWeaverUIFoundation", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverUIFoundation.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverUIFoundation" ],
    [ "WitWeaverUnityAudioProvider", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverUnityAudioProvider.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverUnityAudioProvider" ],
    [ "WitWeaverUnityAudioReference", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverUnityAudioReference.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverUnityAudioReference" ],
    [ "WitWeaverYamlDiagnostic", "structWolfstagInteractive_1_1WitWeaver_1_1WitWeaverYamlDiagnostic.html", "structWolfstagInteractive_1_1WitWeaver_1_1WitWeaverYamlDiagnostic" ],
    [ "WitWeaverYamlLoader", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverYamlLoader.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverYamlLoader" ],
    [ "WitWeaverYamlParser", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverYamlParser.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverYamlParser" ],
    [ "WitWeaverYamlPreprocessor", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverYamlPreprocessor.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverYamlPreprocessor" ],
    [ "WitWeaverYamlSerializer", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverYamlSerializer.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverYamlSerializer" ],
    [ "WitWeaverYamlUtilities", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverYamlUtilities.html", "classWolfstagInteractive_1_1WitWeaver_1_1WitWeaverYamlUtilities" ],
    [ "WorldPointBehaviour", "classWolfstagInteractive_1_1WitWeaver_1_1WorldPointBehaviour.html", "classWolfstagInteractive_1_1WitWeaver_1_1WorldPointBehaviour" ],
    [ "AnimatorControlMode", "namespaceWolfstagInteractive_1_1WitWeaver.html#a96691e3a07f6a13fbeff0ea508469926", [
      [ "PlayState", "namespaceWolfstagInteractive_1_1WitWeaver.html#a96691e3a07f6a13fbeff0ea508469926a2ba7455eb5d0d0e4eee971e8427d3192", null ],
      [ "SetTrigger", "namespaceWolfstagInteractive_1_1WitWeaver.html#a96691e3a07f6a13fbeff0ea508469926afa615a3c52952f3a4273b2d40f02ba90", null ]
    ] ],
    [ "AnimatorParameterType", "namespaceWolfstagInteractive_1_1WitWeaver.html#ab2800abc6045cb6183a95fb3a1afa66e", [
      [ "Bool", "namespaceWolfstagInteractive_1_1WitWeaver.html#ab2800abc6045cb6183a95fb3a1afa66eac26f15e86e3de4c398a8273272aba034", null ],
      [ "Int", "namespaceWolfstagInteractive_1_1WitWeaver.html#ab2800abc6045cb6183a95fb3a1afa66ea1686a6c336b71b36d77354cea19a8b52", null ],
      [ "Float", "namespaceWolfstagInteractive_1_1WitWeaver.html#ab2800abc6045cb6183a95fb3a1afa66ea22ae0e2b89e5e3d477f988cc36d3272b", null ],
      [ "Trigger", "namespaceWolfstagInteractive_1_1WitWeaver.html#ab2800abc6045cb6183a95fb3a1afa66eaf698f67f5666aff10729d8a1cb1c14d2", null ]
    ] ],
    [ "AudioBackend", "namespaceWolfstagInteractive_1_1WitWeaver.html#a3e381fc89b900f252a49211e261905b9", [
      [ "UnityAudioSource", "namespaceWolfstagInteractive_1_1WitWeaver.html#a3e381fc89b900f252a49211e261905b9ab130bc76c2f16f668ac56d0dba7358e8", null ],
      [ "FMOD", "namespaceWolfstagInteractive_1_1WitWeaver.html#a3e381fc89b900f252a49211e261905b9a83ee8e4cce253ad1c7e7b1c78dbc6d9d", null ],
      [ "Wwise", "namespaceWolfstagInteractive_1_1WitWeaver.html#a3e381fc89b900f252a49211e261905b9a7a31acb2c467eb688fd6ed06da7572d4", null ],
      [ "Custom", "namespaceWolfstagInteractive_1_1WitWeaver.html#a3e381fc89b900f252a49211e261905b9a90589c47f06eb971d548591f23c285af", null ]
    ] ],
    [ "AudioManifestMode", "namespaceWolfstagInteractive_1_1WitWeaver.html#a4f683f4a0bf76467e5f6239f9db12f80", [
      [ "ConversationDriven", "namespaceWolfstagInteractive_1_1WitWeaver.html#a4f683f4a0bf76467e5f6239f9db12f80ad7f90f420d777f38cd06645227d88299", null ],
      [ "Standalone", "namespaceWolfstagInteractive_1_1WitWeaver.html#a4f683f4a0bf76467e5f6239f9db12f80a5c80f101108a356211fcb26b3f83eabb", null ]
    ] ],
    [ "ConversationContainerMode", "namespaceWolfstagInteractive_1_1WitWeaver.html#ae1aea77b9fa3e545171670e13ce411f1", [
      [ "Playlist", "namespaceWolfstagInteractive_1_1WitWeaver.html#ae1aea77b9fa3e545171670e13ce411f1abfb6800020a06f5986570499d33f3ce5", null ],
      [ "Selector", "namespaceWolfstagInteractive_1_1WitWeaver.html#ae1aea77b9fa3e545171670e13ce411f1a0c3cd33e7bf626da4897316a7158a7a4", null ]
    ] ],
    [ "ConversationPresentationMode", "namespaceWolfstagInteractive_1_1WitWeaver.html#aa6fba628375d3c51c0c5e5d0d8abd5f2", [
      [ "AudioAndText", "namespaceWolfstagInteractive_1_1WitWeaver.html#aa6fba628375d3c51c0c5e5d0d8abd5f2a0deda2115c0b9702adea1ad008b57b1e", null ],
      [ "AudioOnly", "namespaceWolfstagInteractive_1_1WitWeaver.html#aa6fba628375d3c51c0c5e5d0d8abd5f2ab9d4248c090a6c8049241b68c6dd205f", null ],
      [ "TextOnly", "namespaceWolfstagInteractive_1_1WitWeaver.html#aa6fba628375d3c51c0c5e5d0d8abd5f2a7fab5811b7359cf61d2cbb37b469d431", null ]
    ] ],
    [ "ConversationSelectionMode", "namespaceWolfstagInteractive_1_1WitWeaver.html#a86928d14265ac487c9ad4ea9f8b33b0f", [
      [ "First", "namespaceWolfstagInteractive_1_1WitWeaver.html#a86928d14265ac487c9ad4ea9f8b33b0fa7fb55ed0b7a30342ba6da306428cae04", null ],
      [ "Sequential", "namespaceWolfstagInteractive_1_1WitWeaver.html#a86928d14265ac487c9ad4ea9f8b33b0faa7e82daa7280af25afbaa076ac16eb1e", null ],
      [ "Random", "namespaceWolfstagInteractive_1_1WitWeaver.html#a86928d14265ac487c9ad4ea9f8b33b0fa64663f4646781c9c0110838b905daa23", null ],
      [ "WeightedRandom", "namespaceWolfstagInteractive_1_1WitWeaver.html#a86928d14265ac487c9ad4ea9f8b33b0fadb1e5179aef662aa5e3238520c223405", null ]
    ] ],
    [ "DiagnosticSeverity", "namespaceWolfstagInteractive_1_1WitWeaver.html#aba233efcf0dc503da83f55bc329bfdad", [
      [ "Error", "namespaceWolfstagInteractive_1_1WitWeaver.html#aba233efcf0dc503da83f55bc329bfdada902b0d55fddef6f8d651fe1035b7d4bd", null ],
      [ "Warning", "namespaceWolfstagInteractive_1_1WitWeaver.html#aba233efcf0dc503da83f55bc329bfdada0eaadb4fcb48a0a0ed7bc9868be9fbaa", null ]
    ] ],
    [ "ExcelFormulaCellBehavior", "namespaceWolfstagInteractive_1_1WitWeaver.html#a846b784e97150f2611c3f6534819ec52", [
      [ "UseCachedValue", "namespaceWolfstagInteractive_1_1WitWeaver.html#a846b784e97150f2611c3f6534819ec52a7a8fe460a57fbb44e72aae3c2c374694", null ],
      [ "TreatAsError", "namespaceWolfstagInteractive_1_1WitWeaver.html#a846b784e97150f2611c3f6534819ec52a61e205231d27196d52b04475d38c944d", null ],
      [ "SkipRow", "namespaceWolfstagInteractive_1_1WitWeaver.html#a846b784e97150f2611c3f6534819ec52a9bd180aa0636dc56e4ba452d3c23aa0b", null ]
    ] ],
    [ "FlipbookLoopMode", "namespaceWolfstagInteractive_1_1WitWeaver.html#a0ede85a7df4c388d435d09af7311b51c", [
      [ "Loop", "namespaceWolfstagInteractive_1_1WitWeaver.html#a0ede85a7df4c388d435d09af7311b51ca89d7b10cb4238977d2b523dfd9ea7745", null ],
      [ "Once", "namespaceWolfstagInteractive_1_1WitWeaver.html#a0ede85a7df4c388d435d09af7311b51cae1a9dc9f23534e63de9df0d540ac1611", null ],
      [ "PingPong", "namespaceWolfstagInteractive_1_1WitWeaver.html#a0ede85a7df4c388d435d09af7311b51ca99e52704462d3580db3528cad7ea9660", null ]
    ] ],
    [ "RepresentationRole", "namespaceWolfstagInteractive_1_1WitWeaver.html#a2c0284e0112a2151d5d9850f6dfea983", [
      [ "Speaker", "namespaceWolfstagInteractive_1_1WitWeaver.html#a2c0284e0112a2151d5d9850f6dfea983a22cc65fdfc4417d64127a3a2c12853d0", null ],
      [ "Visible", "namespaceWolfstagInteractive_1_1WitWeaver.html#a2c0284e0112a2151d5d9850f6dfea983aec24d78ce33048dc73a2b6b1a0690192", null ]
    ] ],
    [ "TextSourceKind", "namespaceWolfstagInteractive_1_1WitWeaver.html#abac8f10b4f4865e1e0588f061e706af6", [
      [ "AssignedTextAsset", "namespaceWolfstagInteractive_1_1WitWeaver.html#abac8f10b4f4865e1e0588f061e706af6acc4cf545e0f024d2cb9a60292a4d7d71", null ],
      [ "Persistent", "namespaceWolfstagInteractive_1_1WitWeaver.html#abac8f10b4f4865e1e0588f061e706af6a5fe7b9358c9cb1b9eaa8d5aec000def4", null ],
      [ "Addressables", "namespaceWolfstagInteractive_1_1WitWeaver.html#abac8f10b4f4865e1e0588f061e706af6a684342ec417e5a323fdaf24a6b5f8187", null ],
      [ "Resources", "namespaceWolfstagInteractive_1_1WitWeaver.html#abac8f10b4f4865e1e0588f061e706af6addcf50c29294d4414f3f7c1bbc892cb5", null ]
    ] ],
    [ "WitWeaverSpawnTiming", "namespaceWolfstagInteractive_1_1WitWeaver.html#a258635dc439a89a2e1ed1295ccfbedf7", [
      [ "OnConversationBegin", "namespaceWolfstagInteractive_1_1WitWeaver.html#a258635dc439a89a2e1ed1295ccfbedf7aa56d9bc90ba3312d9a8243ecca85b620", null ],
      [ "OnFirstAppearance", "namespaceWolfstagInteractive_1_1WitWeaver.html#a258635dc439a89a2e1ed1295ccfbedf7a5bc97530fef6d11a55c783eca0b0d40c", null ]
    ] ],
    [ "WitWeaverStartMode", "namespaceWolfstagInteractive_1_1WitWeaver.html#a87dcb6bf60d45aa8479404ec212b7ba6", [
      [ "Fresh", "namespaceWolfstagInteractive_1_1WitWeaver.html#a87dcb6bf60d45aa8479404ec212b7ba6afe8965a9748c1bc48af1711be837124e", null ],
      [ "Resume", "namespaceWolfstagInteractive_1_1WitWeaver.html#a87dcb6bf60d45aa8479404ec212b7ba6af1cefec9e2196c672a622347f1fbc325", null ],
      [ "Restart", "namespaceWolfstagInteractive_1_1WitWeaver.html#a87dcb6bf60d45aa8479404ec212b7ba6a51cfbcff36da74a9fc47f3a5140f99f2", null ]
    ] ]
];