var namespace_wolfstag_interactive_1_1_convo_core =
[
    [ "Editor", "namespace_wolfstag_interactive_1_1_convo_core_1_1_editor.html", "namespace_wolfstag_interactive_1_1_convo_core_1_1_editor" ],
    [ "BaseDialogueLineAction", "class_wolfstag_interactive_1_1_convo_core_1_1_base_dialogue_line_action.html", "class_wolfstag_interactive_1_1_convo_core_1_1_base_dialogue_line_action" ],
    [ "CharacterRepresentationBase", "class_wolfstag_interactive_1_1_convo_core_1_1_character_representation_base.html", "class_wolfstag_interactive_1_1_convo_core_1_1_character_representation_base" ],
    [ "ContainerInput", "class_wolfstag_interactive_1_1_convo_core_1_1_container_input.html", "class_wolfstag_interactive_1_1_convo_core_1_1_container_input" ],
    [ "ConversationBranchResult", "struct_wolfstag_interactive_1_1_convo_core_1_1_conversation_branch_result.html", "struct_wolfstag_interactive_1_1_convo_core_1_1_conversation_branch_result" ],
    [ "ConversationContainer", "class_wolfstag_interactive_1_1_convo_core_1_1_conversation_container.html", "class_wolfstag_interactive_1_1_convo_core_1_1_conversation_container" ],
    [ "ConversationContainerRuntime", "class_wolfstag_interactive_1_1_convo_core_1_1_conversation_container_runtime.html", "class_wolfstag_interactive_1_1_convo_core_1_1_conversation_container_runtime" ],
    [ "ConvoCore", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core" ],
    [ "ConvoCoreAddressablesUtil", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_addressables_util.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_addressables_util" ],
    [ "ConvoCoreCharacterDisplayBase", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_character_display_base.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_character_display_base" ],
    [ "ConvoCoreCharacterExpression", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_character_expression.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_character_expression" ],
    [ "ConvoCoreCharacterProfileBaseData", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_character_profile_base_data.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_character_profile_base_data" ],
    [ "ConvoCoreConversationData", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_conversation_data.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_conversation_data" ],
    [ "ConvoCoreDialogueHistoryUI", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_history_u_i.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_history_u_i" ],
    [ "ConvoCoreDialogueLineActionDialogueLineActionGroup", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_line_action_dialogue_line_action_group.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_line_action_dialogue_line_action_group" ],
    [ "ConvoCoreDialogueLineActionEnableDisableGameObject", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_line_action_enable_disable_game_object.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_line_action_enable_disable_game_object" ],
    [ "ConvoCoreDialogueLineActionFadeInOutSpriteRenderer", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_line_action_fade_in_out_sprite_renderer.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_line_action_fade_in_out_sprite_renderer" ],
    [ "ConvoCoreDialogueLineActionInstantiatePrefab", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_line_action_instantiate_prefab.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_line_action_instantiate_prefab" ],
    [ "ConvoCoreDialogueLineActionModifyTransform", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_line_action_modify_transform.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_line_action_modify_transform" ],
    [ "ConvoCoreDialogueLineActionPlayAudioClip", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_line_action_play_audio_clip.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_line_action_play_audio_clip" ],
    [ "ConvoCoreDialogueLocalizationHandler", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_localization_handler.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_dialogue_localization_handler" ],
    [ "ConvoCoreHistoryRendererProfile", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_history_renderer_profile.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_history_renderer_profile" ],
    [ "ConvoCoreHistoryRendererRegistry", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_history_renderer_registry.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_history_renderer_registry" ],
    [ "ConvoCoreLanguageManager", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_language_manager.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_language_manager" ],
    [ "ConvoCoreLanguageSettings", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_language_settings.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_language_settings" ],
    [ "ConvoCoreLanguageSettingsLoader", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_language_settings_loader.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_language_settings_loader" ],
    [ "ConvoCoreLineID", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_line_i_d.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_line_i_d" ],
    [ "ConvoCoreLineIDUtility", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_line_i_d_utility.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_line_i_d_utility" ],
    [ "ConvoCorePrefabPool", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_prefab_pool.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_prefab_pool" ],
    [ "ConvoCorePrefabRepresentationSpawner", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_prefab_representation_spawner.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_prefab_representation_spawner" ],
    [ "ConvoCoreSampleUI", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_sample_u_i.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_sample_u_i" ],
    [ "ConvoCoreSettings", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_settings.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_settings" ],
    [ "ConvoCoreUIFoundation", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_u_i_foundation.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_u_i_foundation" ],
    [ "ConvoCoreYamlLoader", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_yaml_loader.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_yaml_loader" ],
    [ "ConvoCoreYamlParser", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_yaml_parser.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_yaml_parser" ],
    [ "ConvoCoreYamlSerializer", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_yaml_serializer.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_yaml_serializer" ],
    [ "ConvoCoreYamlUtilities", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_yaml_utilities.html", "class_wolfstag_interactive_1_1_convo_core_1_1_convo_core_yaml_utilities" ],
    [ "DefaultConversationContext", "class_wolfstag_interactive_1_1_convo_core_1_1_default_conversation_context.html", "class_wolfstag_interactive_1_1_convo_core_1_1_default_conversation_context" ],
    [ "DialogueHistoryEntry", "class_wolfstag_interactive_1_1_convo_core_1_1_dialogue_history_entry.html", "class_wolfstag_interactive_1_1_convo_core_1_1_dialogue_history_entry" ],
    [ "DialogueHistoryRendererContext", "struct_wolfstag_interactive_1_1_convo_core_1_1_dialogue_history_renderer_context.html", "struct_wolfstag_interactive_1_1_convo_core_1_1_dialogue_history_renderer_context" ],
    [ "DialogueLineDisplayOptions", "class_wolfstag_interactive_1_1_convo_core_1_1_dialogue_line_display_options.html", "class_wolfstag_interactive_1_1_convo_core_1_1_dialogue_line_display_options" ],
    [ "DialogueYamlConfig", "class_wolfstag_interactive_1_1_convo_core_1_1_dialogue_yaml_config.html", "class_wolfstag_interactive_1_1_convo_core_1_1_dialogue_yaml_config" ],
    [ "ExpressionIDSelectorAttribute", "class_wolfstag_interactive_1_1_convo_core_1_1_expression_i_d_selector_attribute.html", "class_wolfstag_interactive_1_1_convo_core_1_1_expression_i_d_selector_attribute" ],
    [ "GameObjectHelper", "class_wolfstag_interactive_1_1_convo_core_1_1_game_object_helper.html", "class_wolfstag_interactive_1_1_convo_core_1_1_game_object_helper" ],
    [ "GameObjectReference", "class_wolfstag_interactive_1_1_convo_core_1_1_game_object_reference.html", "class_wolfstag_interactive_1_1_convo_core_1_1_game_object_reference" ],
    [ "IConversationContext", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_conversation_context.html", null ],
    [ "IConvoCoreCharacterDisplay", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_character_display.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_character_display" ],
    [ "IConvoCoreFadeIn", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_fade_in.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_fade_in" ],
    [ "IConvoCoreFadeOut", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_fade_out.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_fade_out" ],
    [ "IConvoCoreHistoryRenderer", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_history_renderer.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_history_renderer" ],
    [ "IConvoCoreLanguageSettingsLoader", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_language_settings_loader.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_language_settings_loader" ],
    [ "IConvoCoreRepresentationInitializable", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_representation_initializable.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_representation_initializable" ],
    [ "IConvoCoreRunner", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_runner.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_core_runner" ],
    [ "IConvoInput", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_input.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_convo_input" ],
    [ "IDialogueHistoryOutput", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_dialogue_history_output.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_dialogue_history_output" ],
    [ "IDialogueHistoryOutputPrefab", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_dialogue_history_output_prefab.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_dialogue_history_output_prefab" ],
    [ "IDialogueLineEditorCustomizable", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_dialogue_line_editor_customizable.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_dialogue_line_editor_customizable" ],
    [ "IEditorPreviewableRepresentation", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_editor_previewable_representation.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_editor_previewable_representation" ],
    [ "IUIFoundation", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_u_i_foundation.html", "interface_wolfstag_interactive_1_1_convo_core_1_1_i_u_i_foundation" ],
    [ "LocalizedDialogueResult", "class_wolfstag_interactive_1_1_convo_core_1_1_localized_dialogue_result.html", "class_wolfstag_interactive_1_1_convo_core_1_1_localized_dialogue_result" ],
    [ "PagedListAttribute", "class_wolfstag_interactive_1_1_convo_core_1_1_paged_list_attribute.html", "class_wolfstag_interactive_1_1_convo_core_1_1_paged_list_attribute" ],
    [ "PlainTextHistoryRenderer", "class_wolfstag_interactive_1_1_convo_core_1_1_plain_text_history_renderer.html", "class_wolfstag_interactive_1_1_convo_core_1_1_plain_text_history_renderer" ],
    [ "PrefabCharacterRepresentationData", "class_wolfstag_interactive_1_1_convo_core_1_1_prefab_character_representation_data.html", "class_wolfstag_interactive_1_1_convo_core_1_1_prefab_character_representation_data" ],
    [ "PrefabDialogueHistoryOutput", "class_wolfstag_interactive_1_1_convo_core_1_1_prefab_dialogue_history_output.html", "class_wolfstag_interactive_1_1_convo_core_1_1_prefab_dialogue_history_output" ],
    [ "PrefabExpressionMapping", "class_wolfstag_interactive_1_1_convo_core_1_1_prefab_expression_mapping.html", "class_wolfstag_interactive_1_1_convo_core_1_1_prefab_expression_mapping" ],
    [ "PrefabHistoryRenderer", "class_wolfstag_interactive_1_1_convo_core_1_1_prefab_history_renderer.html", "class_wolfstag_interactive_1_1_convo_core_1_1_prefab_history_renderer" ],
    [ "RepresentationExpressionOverride", "class_wolfstag_interactive_1_1_convo_core_1_1_representation_expression_override.html", "class_wolfstag_interactive_1_1_convo_core_1_1_representation_expression_override" ],
    [ "RepresentationPair", "class_wolfstag_interactive_1_1_convo_core_1_1_representation_pair.html", "class_wolfstag_interactive_1_1_convo_core_1_1_representation_pair" ],
    [ "RichTextHistoryRenderer", "class_wolfstag_interactive_1_1_convo_core_1_1_rich_text_history_renderer.html", "class_wolfstag_interactive_1_1_convo_core_1_1_rich_text_history_renderer" ],
    [ "SimplePrefabRepresentationDisplay", "class_wolfstag_interactive_1_1_convo_core_1_1_simple_prefab_representation_display.html", "class_wolfstag_interactive_1_1_convo_core_1_1_simple_prefab_representation_display" ],
    [ "SingleConversationInput", "class_wolfstag_interactive_1_1_convo_core_1_1_single_conversation_input.html", "class_wolfstag_interactive_1_1_convo_core_1_1_single_conversation_input" ],
    [ "SpriteCharacterRepresentationData", "class_wolfstag_interactive_1_1_convo_core_1_1_sprite_character_representation_data.html", "class_wolfstag_interactive_1_1_convo_core_1_1_sprite_character_representation_data" ],
    [ "SpriteExpressionMapping", "class_wolfstag_interactive_1_1_convo_core_1_1_sprite_expression_mapping.html", "class_wolfstag_interactive_1_1_convo_core_1_1_sprite_expression_mapping" ],
    [ "TMPDialogueHistoryOutput", "class_wolfstag_interactive_1_1_convo_core_1_1_t_m_p_dialogue_history_output.html", "class_wolfstag_interactive_1_1_convo_core_1_1_t_m_p_dialogue_history_output" ],
    [ "ConversationContainerMode", "namespace_wolfstag_interactive_1_1_convo_core.html#a6c70857d1accf842107cbea48908d710", [
      [ "Playlist", "namespace_wolfstag_interactive_1_1_convo_core.html#a6c70857d1accf842107cbea48908d710abfb6800020a06f5986570499d33f3ce5", null ],
      [ "Selector", "namespace_wolfstag_interactive_1_1_convo_core.html#a6c70857d1accf842107cbea48908d710a0c3cd33e7bf626da4897316a7158a7a4", null ]
    ] ],
    [ "ConversationSelectionMode", "namespace_wolfstag_interactive_1_1_convo_core.html#a842505d4978372cedbefe3e48d25b707", [
      [ "First", "namespace_wolfstag_interactive_1_1_convo_core.html#a842505d4978372cedbefe3e48d25b707a7fb55ed0b7a30342ba6da306428cae04", null ],
      [ "Sequential", "namespace_wolfstag_interactive_1_1_convo_core.html#a842505d4978372cedbefe3e48d25b707aa7e82daa7280af25afbaa076ac16eb1e", null ],
      [ "Random", "namespace_wolfstag_interactive_1_1_convo_core.html#a842505d4978372cedbefe3e48d25b707a64663f4646781c9c0110838b905daa23", null ],
      [ "WeightedRandom", "namespace_wolfstag_interactive_1_1_convo_core.html#a842505d4978372cedbefe3e48d25b707adb1e5179aef662aa5e3238520c223405", null ]
    ] ],
    [ "DisplaySide", "namespace_wolfstag_interactive_1_1_convo_core.html#a641e3e9ced2cb6f0f0e0ccc6e90318ca", [
      [ "Left", "namespace_wolfstag_interactive_1_1_convo_core.html#a641e3e9ced2cb6f0f0e0ccc6e90318caa945d5e233cf7d6240f6b783b36a374ff", null ],
      [ "Right", "namespace_wolfstag_interactive_1_1_convo_core.html#a641e3e9ced2cb6f0f0e0ccc6e90318caa92b09c7c48c520c3c55e497875da437c", null ],
      [ "Center", "namespace_wolfstag_interactive_1_1_convo_core.html#a641e3e9ced2cb6f0f0e0ccc6e90318caa4f1f6016fc9f3f2353c0cc7c67b292bd", null ]
    ] ],
    [ "DisplaySlot", "namespace_wolfstag_interactive_1_1_convo_core.html#a7672af973360b3e5b2b3259e3f6088ae", [
      [ "Left", "namespace_wolfstag_interactive_1_1_convo_core.html#a7672af973360b3e5b2b3259e3f6088aea945d5e233cf7d6240f6b783b36a374ff", null ],
      [ "Right", "namespace_wolfstag_interactive_1_1_convo_core.html#a7672af973360b3e5b2b3259e3f6088aea92b09c7c48c520c3c55e497875da437c", null ],
      [ "Center", "namespace_wolfstag_interactive_1_1_convo_core.html#a7672af973360b3e5b2b3259e3f6088aea4f1f6016fc9f3f2353c0cc7c67b292bd", null ]
    ] ],
    [ "TextSourceKind", "namespace_wolfstag_interactive_1_1_convo_core.html#ae5e9633d75a8b3c6bf69f6eaa4339485", [
      [ "AssignedTextAsset", "namespace_wolfstag_interactive_1_1_convo_core.html#ae5e9633d75a8b3c6bf69f6eaa4339485acc4cf545e0f024d2cb9a60292a4d7d71", null ],
      [ "Persistent", "namespace_wolfstag_interactive_1_1_convo_core.html#ae5e9633d75a8b3c6bf69f6eaa4339485a5fe7b9358c9cb1b9eaa8d5aec000def4", null ],
      [ "Addressables", "namespace_wolfstag_interactive_1_1_convo_core.html#ae5e9633d75a8b3c6bf69f6eaa4339485a684342ec417e5a323fdaf24a6b5f8187", null ],
      [ "Resources", "namespace_wolfstag_interactive_1_1_convo_core.html#ae5e9633d75a8b3c6bf69f6eaa4339485addcf50c29294d4414f3f7c1bbc892cb5", null ]
    ] ]
];