var namespaceWolfstagInteractive_1_1ConvoCore =
[
    [ "SaveSystem", "namespaceWolfstagInteractive_1_1ConvoCore_1_1SaveSystem.html", "namespaceWolfstagInteractive_1_1ConvoCore_1_1SaveSystem" ],
    [ "AnimatedCharacterRepresentationData", "classWolfstagInteractive_1_1ConvoCore_1_1AnimatedCharacterRepresentationData.html", "classWolfstagInteractive_1_1ConvoCore_1_1AnimatedCharacterRepresentationData" ],
    [ "AnimatedExpressionMapping", "classWolfstagInteractive_1_1ConvoCore_1_1AnimatedExpressionMapping.html", "classWolfstagInteractive_1_1ConvoCore_1_1AnimatedExpressionMapping" ],
    [ "AnimatedExpressionPayload", "classWolfstagInteractive_1_1ConvoCore_1_1AnimatedExpressionPayload.html", "classWolfstagInteractive_1_1ConvoCore_1_1AnimatedExpressionPayload" ],
    [ "AnimatedPlaybackContext", "structWolfstagInteractive_1_1ConvoCore_1_1AnimatedPlaybackContext.html", "structWolfstagInteractive_1_1ConvoCore_1_1AnimatedPlaybackContext" ],
    [ "AnimatorExpressionMapping", "classWolfstagInteractive_1_1ConvoCore_1_1AnimatorExpressionMapping.html", "classWolfstagInteractive_1_1ConvoCore_1_1AnimatorExpressionMapping" ],
    [ "AnimatorPrefabAnimationPayload", "classWolfstagInteractive_1_1ConvoCore_1_1AnimatorPrefabAnimationPayload.html", "classWolfstagInteractive_1_1ConvoCore_1_1AnimatorPrefabAnimationPayload" ],
    [ "BaseDialogueLineAction", "classWolfstagInteractive_1_1ConvoCore_1_1BaseDialogueLineAction.html", "classWolfstagInteractive_1_1ConvoCore_1_1BaseDialogueLineAction" ],
    [ "BaseExpressionAction", "classWolfstagInteractive_1_1ConvoCore_1_1BaseExpressionAction.html", "classWolfstagInteractive_1_1ConvoCore_1_1BaseExpressionAction" ],
    [ "BlendShapeExpressionMapping", "classWolfstagInteractive_1_1ConvoCore_1_1BlendShapeExpressionMapping.html", "classWolfstagInteractive_1_1ConvoCore_1_1BlendShapeExpressionMapping" ],
    [ "BlendShapeTarget", "classWolfstagInteractive_1_1ConvoCore_1_1BlendShapeTarget.html", "classWolfstagInteractive_1_1ConvoCore_1_1BlendShapeTarget" ],
    [ "CameraRelativeBehaviour", "classWolfstagInteractive_1_1ConvoCore_1_1CameraRelativeBehaviour.html", "classWolfstagInteractive_1_1ConvoCore_1_1CameraRelativeBehaviour" ],
    [ "CharacterBehaviourContext", "structWolfstagInteractive_1_1ConvoCore_1_1CharacterBehaviourContext.html", "structWolfstagInteractive_1_1ConvoCore_1_1CharacterBehaviourContext" ],
    [ "CharacterRepresentationBase", "classWolfstagInteractive_1_1ConvoCore_1_1CharacterRepresentationBase.html", "classWolfstagInteractive_1_1ConvoCore_1_1CharacterRepresentationBase" ],
    [ "ChoiceResult", "classWolfstagInteractive_1_1ConvoCore_1_1ChoiceResult.html", "classWolfstagInteractive_1_1ConvoCore_1_1ChoiceResult" ],
    [ "ContainerInput", "classWolfstagInteractive_1_1ConvoCore_1_1ContainerInput.html", "classWolfstagInteractive_1_1ConvoCore_1_1ContainerInput" ],
    [ "ConversationBranchResult", "structWolfstagInteractive_1_1ConvoCore_1_1ConversationBranchResult.html", "structWolfstagInteractive_1_1ConvoCore_1_1ConversationBranchResult" ],
    [ "ConversationContainer", "classWolfstagInteractive_1_1ConvoCore_1_1ConversationContainer.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConversationContainer" ],
    [ "ConversationContainerRuntime", "classWolfstagInteractive_1_1ConvoCore_1_1ConversationContainerRuntime.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConversationContainerRuntime" ],
    [ "ConvoAudioReference", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoAudioReference.html", null ],
    [ "ConvoCore", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCore.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCore" ],
    [ "ConvoCoreActionOnlyDisplay", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreActionOnlyDisplay.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreActionOnlyDisplay" ],
    [ "ConvoCoreAddressablesUtil", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAddressablesUtil.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAddressablesUtil" ],
    [ "ConvoCoreAnimatedPortraitPlayer", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAnimatedPortraitPlayer.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAnimatedPortraitPlayer" ],
    [ "ConvoCoreAnimatorBehaviour", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAnimatorBehaviour.html", null ],
    [ "ConvoCoreAnimatorDisplay", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAnimatorDisplay.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAnimatorDisplay" ],
    [ "ConvoCoreAudioEventKeyReference", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAudioEventKeyReference.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAudioEventKeyReference" ],
    [ "ConvoCoreAudioManifest", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAudioManifest.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreAudioManifest" ],
    [ "ConvoCoreBlendShapeDisplay", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreBlendShapeDisplay.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreBlendShapeDisplay" ],
    [ "ConvoCoreCameraRelativePosition", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCameraRelativePosition.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCameraRelativePosition" ],
    [ "ConvoCoreCharacterBehaviour", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCharacterBehaviour.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCharacterBehaviour" ],
    [ "ConvoCoreCharacterDisplayBase", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCharacterDisplayBase.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCharacterDisplayBase" ],
    [ "ConvoCoreCharacterProfileBaseData", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCharacterProfileBaseData.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreCharacterProfileBaseData" ],
    [ "ConvoCoreConversationData", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreConversationData.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreConversationData" ],
    [ "ConvoCoreDialogueHistoryUI", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueHistoryUI.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueHistoryUI" ],
    [ "ConvoCoreDialogueLineActionDialogueLineActionGroup", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionDialogueLineActionGroup.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionDialogueLineActionGroup" ],
    [ "ConvoCoreDialogueLineActionEnableDisableGameObject", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionEnableDisableGameObject.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionEnableDisableGameObject" ],
    [ "ConvoCoreDialogueLineActionFadeInOutSpriteRenderer", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionFadeInOutSpriteRenderer.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionFadeInOutSpriteRenderer" ],
    [ "ConvoCoreDialogueLineActionInstantiatePrefab", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionInstantiatePrefab.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionInstantiatePrefab" ],
    [ "ConvoCoreDialogueLineActionModifyTransform", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionModifyTransform.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionModifyTransform" ],
    [ "ConvoCoreDialogueLineActionPlayAudioClip", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionPlayAudioClip.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLineActionPlayAudioClip" ],
    [ "ConvoCoreDialogueLocalizationHandler", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLocalizationHandler.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreDialogueLocalizationHandler" ],
    [ "ConvoCoreFollowTarget", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreFollowTarget.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreFollowTarget" ],
    [ "ConvoCoreHistoryRendererProfile", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreHistoryRendererProfile.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreHistoryRendererProfile" ],
    [ "ConvoCoreHistoryRendererRegistry", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreHistoryRendererRegistry.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreHistoryRendererRegistry" ],
    [ "ConvoCoreLanguageManager", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLanguageManager.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLanguageManager" ],
    [ "ConvoCoreLanguageSettings", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLanguageSettings.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLanguageSettings" ],
    [ "ConvoCoreLanguageSettingsLoader", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLanguageSettingsLoader.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLanguageSettingsLoader" ],
    [ "ConvoCoreLineID", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLineID.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLineID" ],
    [ "ConvoCoreLineIDUtility", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLineIDUtility.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreLineIDUtility" ],
    [ "ConvoCorePrefabPool", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCorePrefabPool.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCorePrefabPool" ],
    [ "ConvoCorePrefabRepresentationSpawner", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCorePrefabRepresentationSpawner.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCorePrefabRepresentationSpawner" ],
    [ "ConvoCoreSampleUI3D", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSampleUI3D.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSampleUI3D" ],
    [ "ConvoCoreSampleUICanvas", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSampleUICanvas.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSampleUICanvas" ],
    [ "ConvoCoreSceneCharacterRegistrant", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSceneCharacterRegistrant.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSceneCharacterRegistrant" ],
    [ "ConvoCoreSceneCharacterRegistry", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSceneCharacterRegistry.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSceneCharacterRegistry" ],
    [ "ConvoCoreSettings", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSettings.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSettings" ],
    [ "ConvoCoreSimpleFade", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSimpleFade.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSimpleFade" ],
    [ "ConvoCoreSpawnPoint", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSpawnPoint.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSpawnPoint" ],
    [ "ConvoCoreSpawnPointRegistry", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSpawnPointRegistry.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreSpawnPointRegistry" ],
    [ "ConvoCoreTransformLerp", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreTransformLerp.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreTransformLerp" ],
    [ "ConvoCoreUIFoundation", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreUIFoundation.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreUIFoundation" ],
    [ "ConvoCoreUnityAudioProvider", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreUnityAudioProvider.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreUnityAudioProvider" ],
    [ "ConvoCoreUnityAudioReference", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreUnityAudioReference.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreUnityAudioReference" ],
    [ "ConvoCoreYamlDiagnostic", "structWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlDiagnostic.html", "structWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlDiagnostic" ],
    [ "ConvoCoreYamlLoader", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlLoader.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlLoader" ],
    [ "ConvoCoreYamlParser", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlParser.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlParser" ],
    [ "ConvoCoreYamlPreprocessor", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlPreprocessor.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlPreprocessor" ],
    [ "ConvoCoreYamlSerializer", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlSerializer.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlSerializer" ],
    [ "ConvoCoreYamlUtilities", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlUtilities.html", "classWolfstagInteractive_1_1ConvoCore_1_1ConvoCoreYamlUtilities" ],
    [ "ConvoStartContext", "structWolfstagInteractive_1_1ConvoCore_1_1ConvoStartContext.html", "structWolfstagInteractive_1_1ConvoCore_1_1ConvoStartContext" ],
    [ "DefaultConversationContext", "classWolfstagInteractive_1_1ConvoCore_1_1DefaultConversationContext.html", "classWolfstagInteractive_1_1ConvoCore_1_1DefaultConversationContext" ],
    [ "DialogueHistoryEntry", "classWolfstagInteractive_1_1ConvoCore_1_1DialogueHistoryEntry.html", "classWolfstagInteractive_1_1ConvoCore_1_1DialogueHistoryEntry" ],
    [ "DialogueHistoryRendererContext", "structWolfstagInteractive_1_1ConvoCore_1_1DialogueHistoryRendererContext.html", "structWolfstagInteractive_1_1ConvoCore_1_1DialogueHistoryRendererContext" ],
    [ "DialogueLineDisplayOptions", "classWolfstagInteractive_1_1ConvoCore_1_1DialogueLineDisplayOptions.html", "classWolfstagInteractive_1_1ConvoCore_1_1DialogueLineDisplayOptions" ],
    [ "DialogueYamlConfig", "classWolfstagInteractive_1_1ConvoCore_1_1DialogueYamlConfig.html", "classWolfstagInteractive_1_1ConvoCore_1_1DialogueYamlConfig" ],
    [ "ExpressionActionContext", "structWolfstagInteractive_1_1ConvoCore_1_1ExpressionActionContext.html", "structWolfstagInteractive_1_1ConvoCore_1_1ExpressionActionContext" ],
    [ "ExpressionIDSelectorAttribute", "classWolfstagInteractive_1_1ConvoCore_1_1ExpressionIDSelectorAttribute.html", "classWolfstagInteractive_1_1ConvoCore_1_1ExpressionIDSelectorAttribute" ],
    [ "ExternalBehaviour", "classWolfstagInteractive_1_1ConvoCore_1_1ExternalBehaviour.html", "classWolfstagInteractive_1_1ConvoCore_1_1ExternalBehaviour" ],
    [ "FlipbookAnimationPayload", "classWolfstagInteractive_1_1ConvoCore_1_1FlipbookAnimationPayload.html", "classWolfstagInteractive_1_1ConvoCore_1_1FlipbookAnimationPayload" ],
    [ "FollowTargetBehaviour", "classWolfstagInteractive_1_1ConvoCore_1_1FollowTargetBehaviour.html", "classWolfstagInteractive_1_1ConvoCore_1_1FollowTargetBehaviour" ],
    [ "GameObjectHelper", "classWolfstagInteractive_1_1ConvoCore_1_1GameObjectHelper.html", "classWolfstagInteractive_1_1ConvoCore_1_1GameObjectHelper" ],
    [ "GameObjectReference", "classWolfstagInteractive_1_1ConvoCore_1_1GameObjectReference.html", "classWolfstagInteractive_1_1ConvoCore_1_1GameObjectReference" ],
    [ "IAnimatedExpressionPlayback", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IAnimatedExpressionPlayback.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IAnimatedExpressionPlayback" ],
    [ "IAnimatedPortraitSurface", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IAnimatedPortraitSurface.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IAnimatedPortraitSurface" ],
    [ "IConversationContext", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConversationContext.html", null ],
    [ "IConvoAudioProvider", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoAudioProvider.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoAudioProvider" ],
    [ "IConvoCoreCharacterDisplay", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreCharacterDisplay.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreCharacterDisplay" ],
    [ "IConvoCoreFadeIn", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreFadeIn.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreFadeIn" ],
    [ "IConvoCoreFadeOut", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreFadeOut.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreFadeOut" ],
    [ "IConvoCoreHistoryRenderer", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreHistoryRenderer.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreHistoryRenderer" ],
    [ "IConvoCoreLanguageSettingsLoader", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreLanguageSettingsLoader.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreLanguageSettingsLoader" ],
    [ "IConvoCoreRepresentationInitializable", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreRepresentationInitializable.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreRepresentationInitializable" ],
    [ "IConvoCoreRunner", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreRunner.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreRunner" ],
    [ "IConvoCoreSpreadsheetReader", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreSpreadsheetReader.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoCoreSpreadsheetReader" ],
    [ "IConvoInput", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoInput.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoInput" ],
    [ "IConvoStartContextProvider", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoStartContextProvider.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IConvoStartContextProvider" ],
    [ "IDialogueHistoryOutput", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueHistoryOutput.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueHistoryOutput" ],
    [ "IDialogueHistoryOutputPrefab", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueHistoryOutputPrefab.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IDialogueHistoryOutputPrefab" ],
    [ "IExpressionCatalogProvider", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IExpressionCatalogProvider.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IExpressionCatalogProvider" ],
    [ "IUIFoundation", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IUIFoundation.html", "interfaceWolfstagInteractive_1_1ConvoCore_1_1IUIFoundation" ],
    [ "LocalizedDialogueResult", "classWolfstagInteractive_1_1ConvoCore_1_1LocalizedDialogueResult.html", "classWolfstagInteractive_1_1ConvoCore_1_1LocalizedDialogueResult" ],
    [ "PagedListAttribute", "classWolfstagInteractive_1_1ConvoCore_1_1PagedListAttribute.html", "classWolfstagInteractive_1_1ConvoCore_1_1PagedListAttribute" ],
    [ "ParticipantConfigurationSlot", "classWolfstagInteractive_1_1ConvoCore_1_1ParticipantConfigurationSlot.html", "classWolfstagInteractive_1_1ConvoCore_1_1ParticipantConfigurationSlot" ],
    [ "PlainTextHistoryRenderer", "classWolfstagInteractive_1_1ConvoCore_1_1PlainTextHistoryRenderer.html", "classWolfstagInteractive_1_1ConvoCore_1_1PlainTextHistoryRenderer" ],
    [ "PrefabCharacterConfigurationEntry", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabCharacterConfigurationEntry.html", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabCharacterConfigurationEntry" ],
    [ "PrefabCharacterRepresentationData", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabCharacterRepresentationData.html", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabCharacterRepresentationData" ],
    [ "PrefabDialogueHistoryOutput", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabDialogueHistoryOutput.html", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabDialogueHistoryOutput" ],
    [ "PrefabExpressionMapping", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabExpressionMapping.html", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabExpressionMapping" ],
    [ "PrefabHistoryRenderer", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabHistoryRenderer.html", "classWolfstagInteractive_1_1ConvoCore_1_1PrefabHistoryRenderer" ],
    [ "PreprocessorResult", "classWolfstagInteractive_1_1ConvoCore_1_1PreprocessorResult.html", "classWolfstagInteractive_1_1ConvoCore_1_1PreprocessorResult" ],
    [ "RepresentationPair", "classWolfstagInteractive_1_1ConvoCore_1_1RepresentationPair.html", "classWolfstagInteractive_1_1ConvoCore_1_1RepresentationPair" ],
    [ "RichTextHistoryRenderer", "classWolfstagInteractive_1_1ConvoCore_1_1RichTextHistoryRenderer.html", "classWolfstagInteractive_1_1ConvoCore_1_1RichTextHistoryRenderer" ],
    [ "SequencedBehaviour", "classWolfstagInteractive_1_1ConvoCore_1_1SequencedBehaviour.html", "classWolfstagInteractive_1_1ConvoCore_1_1SequencedBehaviour" ],
    [ "SimplePrefabRepresentationDisplay", "classWolfstagInteractive_1_1ConvoCore_1_1SimplePrefabRepresentationDisplay.html", "classWolfstagInteractive_1_1ConvoCore_1_1SimplePrefabRepresentationDisplay" ],
    [ "SingleConversationInput", "classWolfstagInteractive_1_1ConvoCore_1_1SingleConversationInput.html", "classWolfstagInteractive_1_1ConvoCore_1_1SingleConversationInput" ],
    [ "SpreadsheetRowConfig", "classWolfstagInteractive_1_1ConvoCore_1_1SpreadsheetRowConfig.html", "classWolfstagInteractive_1_1ConvoCore_1_1SpreadsheetRowConfig" ],
    [ "SpriteCharacterRepresentationData", "classWolfstagInteractive_1_1ConvoCore_1_1SpriteCharacterRepresentationData.html", "classWolfstagInteractive_1_1ConvoCore_1_1SpriteCharacterRepresentationData" ],
    [ "SpriteExpressionMapping", "classWolfstagInteractive_1_1ConvoCore_1_1SpriteExpressionMapping.html", "classWolfstagInteractive_1_1ConvoCore_1_1SpriteExpressionMapping" ],
    [ "TMPDialogueHistoryOutput", "classWolfstagInteractive_1_1ConvoCore_1_1TMPDialogueHistoryOutput.html", "classWolfstagInteractive_1_1ConvoCore_1_1TMPDialogueHistoryOutput" ],
    [ "TransformLerpBehaviour", "classWolfstagInteractive_1_1ConvoCore_1_1TransformLerpBehaviour.html", "classWolfstagInteractive_1_1ConvoCore_1_1TransformLerpBehaviour" ],
    [ "WorldPointBehaviour", "classWolfstagInteractive_1_1ConvoCore_1_1WorldPointBehaviour.html", "classWolfstagInteractive_1_1ConvoCore_1_1WorldPointBehaviour" ],
    [ "AnimatorControlMode", "namespaceWolfstagInteractive_1_1ConvoCore.html#a375546f4e6d9514a77ab9bd3779529f5", [
      [ "PlayState", "namespaceWolfstagInteractive_1_1ConvoCore.html#a375546f4e6d9514a77ab9bd3779529f5a2ba7455eb5d0d0e4eee971e8427d3192", null ],
      [ "SetTrigger", "namespaceWolfstagInteractive_1_1ConvoCore.html#a375546f4e6d9514a77ab9bd3779529f5afa615a3c52952f3a4273b2d40f02ba90", null ]
    ] ],
    [ "AnimatorParameterType", "namespaceWolfstagInteractive_1_1ConvoCore.html#aca0736f8a2dd132b75254076daa1baa0", [
      [ "Bool", "namespaceWolfstagInteractive_1_1ConvoCore.html#aca0736f8a2dd132b75254076daa1baa0ac26f15e86e3de4c398a8273272aba034", null ],
      [ "Int", "namespaceWolfstagInteractive_1_1ConvoCore.html#aca0736f8a2dd132b75254076daa1baa0a1686a6c336b71b36d77354cea19a8b52", null ],
      [ "Float", "namespaceWolfstagInteractive_1_1ConvoCore.html#aca0736f8a2dd132b75254076daa1baa0a22ae0e2b89e5e3d477f988cc36d3272b", null ],
      [ "Trigger", "namespaceWolfstagInteractive_1_1ConvoCore.html#aca0736f8a2dd132b75254076daa1baa0af698f67f5666aff10729d8a1cb1c14d2", null ]
    ] ],
    [ "AudioBackend", "namespaceWolfstagInteractive_1_1ConvoCore.html#a8ddf95e1f3f9ac3420ef66457a3c4e50", [
      [ "UnityAudioSource", "namespaceWolfstagInteractive_1_1ConvoCore.html#a8ddf95e1f3f9ac3420ef66457a3c4e50ab130bc76c2f16f668ac56d0dba7358e8", null ],
      [ "FMOD", "namespaceWolfstagInteractive_1_1ConvoCore.html#a8ddf95e1f3f9ac3420ef66457a3c4e50a83ee8e4cce253ad1c7e7b1c78dbc6d9d", null ],
      [ "Wwise", "namespaceWolfstagInteractive_1_1ConvoCore.html#a8ddf95e1f3f9ac3420ef66457a3c4e50a7a31acb2c467eb688fd6ed06da7572d4", null ],
      [ "Custom", "namespaceWolfstagInteractive_1_1ConvoCore.html#a8ddf95e1f3f9ac3420ef66457a3c4e50a90589c47f06eb971d548591f23c285af", null ]
    ] ],
    [ "AudioManifestMode", "namespaceWolfstagInteractive_1_1ConvoCore.html#a0cd6501ed9818f514485c79a95be3401", [
      [ "ConversationDriven", "namespaceWolfstagInteractive_1_1ConvoCore.html#a0cd6501ed9818f514485c79a95be3401ad7f90f420d777f38cd06645227d88299", null ],
      [ "Standalone", "namespaceWolfstagInteractive_1_1ConvoCore.html#a0cd6501ed9818f514485c79a95be3401a5c80f101108a356211fcb26b3f83eabb", null ]
    ] ],
    [ "ConversationContainerMode", "namespaceWolfstagInteractive_1_1ConvoCore.html#a6c70857d1accf842107cbea48908d710", [
      [ "Playlist", "namespaceWolfstagInteractive_1_1ConvoCore.html#a6c70857d1accf842107cbea48908d710abfb6800020a06f5986570499d33f3ce5", null ],
      [ "Selector", "namespaceWolfstagInteractive_1_1ConvoCore.html#a6c70857d1accf842107cbea48908d710a0c3cd33e7bf626da4897316a7158a7a4", null ]
    ] ],
    [ "ConversationPresentationMode", "namespaceWolfstagInteractive_1_1ConvoCore.html#a228f0e22800971dc3f26063ce84383c0", [
      [ "AudioAndText", "namespaceWolfstagInteractive_1_1ConvoCore.html#a228f0e22800971dc3f26063ce84383c0a0deda2115c0b9702adea1ad008b57b1e", null ],
      [ "AudioOnly", "namespaceWolfstagInteractive_1_1ConvoCore.html#a228f0e22800971dc3f26063ce84383c0ab9d4248c090a6c8049241b68c6dd205f", null ],
      [ "TextOnly", "namespaceWolfstagInteractive_1_1ConvoCore.html#a228f0e22800971dc3f26063ce84383c0a7fab5811b7359cf61d2cbb37b469d431", null ]
    ] ],
    [ "ConversationSelectionMode", "namespaceWolfstagInteractive_1_1ConvoCore.html#a842505d4978372cedbefe3e48d25b707", [
      [ "First", "namespaceWolfstagInteractive_1_1ConvoCore.html#a842505d4978372cedbefe3e48d25b707a7fb55ed0b7a30342ba6da306428cae04", null ],
      [ "Sequential", "namespaceWolfstagInteractive_1_1ConvoCore.html#a842505d4978372cedbefe3e48d25b707aa7e82daa7280af25afbaa076ac16eb1e", null ],
      [ "Random", "namespaceWolfstagInteractive_1_1ConvoCore.html#a842505d4978372cedbefe3e48d25b707a64663f4646781c9c0110838b905daa23", null ],
      [ "WeightedRandom", "namespaceWolfstagInteractive_1_1ConvoCore.html#a842505d4978372cedbefe3e48d25b707adb1e5179aef662aa5e3238520c223405", null ]
    ] ],
    [ "ConvoCoreSpawnTiming", "namespaceWolfstagInteractive_1_1ConvoCore.html#af50021c14d434054490b385035bdfca8", [
      [ "OnConversationBegin", "namespaceWolfstagInteractive_1_1ConvoCore.html#af50021c14d434054490b385035bdfca8aa56d9bc90ba3312d9a8243ecca85b620", null ],
      [ "OnFirstAppearance", "namespaceWolfstagInteractive_1_1ConvoCore.html#af50021c14d434054490b385035bdfca8a5bc97530fef6d11a55c783eca0b0d40c", null ]
    ] ],
    [ "ConvoStartMode", "namespaceWolfstagInteractive_1_1ConvoCore.html#ab51458c34c46dd42dd277279af380b8b", [
      [ "Fresh", "namespaceWolfstagInteractive_1_1ConvoCore.html#ab51458c34c46dd42dd277279af380b8bafe8965a9748c1bc48af1711be837124e", null ],
      [ "Resume", "namespaceWolfstagInteractive_1_1ConvoCore.html#ab51458c34c46dd42dd277279af380b8baf1cefec9e2196c672a622347f1fbc325", null ],
      [ "Restart", "namespaceWolfstagInteractive_1_1ConvoCore.html#ab51458c34c46dd42dd277279af380b8ba51cfbcff36da74a9fc47f3a5140f99f2", null ]
    ] ],
    [ "DiagnosticSeverity", "namespaceWolfstagInteractive_1_1ConvoCore.html#a6267fa7a81633d66a667dc58b5ee9e5e", [
      [ "Error", "namespaceWolfstagInteractive_1_1ConvoCore.html#a6267fa7a81633d66a667dc58b5ee9e5ea902b0d55fddef6f8d651fe1035b7d4bd", null ],
      [ "Warning", "namespaceWolfstagInteractive_1_1ConvoCore.html#a6267fa7a81633d66a667dc58b5ee9e5ea0eaadb4fcb48a0a0ed7bc9868be9fbaa", null ]
    ] ],
    [ "ExcelFormulaCellBehavior", "namespaceWolfstagInteractive_1_1ConvoCore.html#a94a97dbcb9d0d470cea1b3f05679ee5e", [
      [ "UseCachedValue", "namespaceWolfstagInteractive_1_1ConvoCore.html#a94a97dbcb9d0d470cea1b3f05679ee5ea7a8fe460a57fbb44e72aae3c2c374694", null ],
      [ "TreatAsError", "namespaceWolfstagInteractive_1_1ConvoCore.html#a94a97dbcb9d0d470cea1b3f05679ee5ea61e205231d27196d52b04475d38c944d", null ],
      [ "SkipRow", "namespaceWolfstagInteractive_1_1ConvoCore.html#a94a97dbcb9d0d470cea1b3f05679ee5ea9bd180aa0636dc56e4ba452d3c23aa0b", null ]
    ] ],
    [ "FlipbookLoopMode", "namespaceWolfstagInteractive_1_1ConvoCore.html#abe4580c9b84ba18790160b78384926e5", [
      [ "Loop", "namespaceWolfstagInteractive_1_1ConvoCore.html#abe4580c9b84ba18790160b78384926e5a89d7b10cb4238977d2b523dfd9ea7745", null ],
      [ "Once", "namespaceWolfstagInteractive_1_1ConvoCore.html#abe4580c9b84ba18790160b78384926e5ae1a9dc9f23534e63de9df0d540ac1611", null ],
      [ "PingPong", "namespaceWolfstagInteractive_1_1ConvoCore.html#abe4580c9b84ba18790160b78384926e5a99e52704462d3580db3528cad7ea9660", null ]
    ] ],
    [ "TextSourceKind", "namespaceWolfstagInteractive_1_1ConvoCore.html#ae5e9633d75a8b3c6bf69f6eaa4339485", [
      [ "AssignedTextAsset", "namespaceWolfstagInteractive_1_1ConvoCore.html#ae5e9633d75a8b3c6bf69f6eaa4339485acc4cf545e0f024d2cb9a60292a4d7d71", null ],
      [ "Persistent", "namespaceWolfstagInteractive_1_1ConvoCore.html#ae5e9633d75a8b3c6bf69f6eaa4339485a5fe7b9358c9cb1b9eaa8d5aec000def4", null ],
      [ "Addressables", "namespaceWolfstagInteractive_1_1ConvoCore.html#ae5e9633d75a8b3c6bf69f6eaa4339485a684342ec417e5a323fdaf24a6b5f8187", null ],
      [ "Resources", "namespaceWolfstagInteractive_1_1ConvoCore.html#ae5e9633d75a8b3c6bf69f6eaa4339485addcf50c29294d4414f3f7c1bbc892cb5", null ]
    ] ]
];